wordpress-mobile/WordPressAuthenticator-iOS

WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Model/LoginFields.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Signup/SignupEmailViewController.swift

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/8388
When logging in with `restrictToWPCom` turned on, and the uses selects to login via Google, we now hide the option to login via address when there is an error. This will improve error recovery for these users.
- Login to the app using a self-hosted site
- On the Me tab, tap to login to wpcom
- Chose to login via Google
- Force an error (I modify `googleLoginTapped()` in `LoginEmailViewController`)
- Ensure that the option to retry via site address is gone, and that the other two options still work
- Ensure that the three options all appear and work when login is not restricted to wpcom

Hide address-based option in social errors

---

WordPressAuthenticator/Extensions/UIImage+Assets.swift

This PR updates an misaligned asset reference. 
See issue #9692 on WordPress-iOS repo.

Fix asset reference

---

WordPressAuthenticator/Authenticator/WordPressAuthenticatorDelegateProtocol.swift
WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Signup/SignupGoogleViewController.swift

Just a little bit of housekeeping: the method `sync` has a closure callback, which expects an **Error** optional. However: such parameter is never, not ever used.
In this PR we're simply dropping such parameter.
Please refer to [this WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/9750) for testing steps.
Thanks in advance!!

Updating Authenticator delegate

---

WordPressAuthenticator/Signin/Login2FAViewController.swift

This PR enables the One Time Code textField for iOS 12 autofill.
Testing instructions [detailed here](https://github.com/wordpress-mobile/WordPress-iOS/pull/9767).
@frosty Thanks in advance!!!

Login2FAViewController: Enabling iOS 12 OTP Autofill

---

WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift

Fixes #15 
**Background:** In WCiOS (host app) all UIButton instances had their UIAppearance set with a text color of `wooPurple`. Setting UIAppearance for all UIButton instances causes bugs because it's too general. For example, the Logout button should be a dark red "destructive action" color, but it's purple. 
1. check out this branch
2. check out the host app branch: https://github.com/woocommerce/woocommerce-ios/pull/154
3. delete any existing WCiOS app builds
4. open WCiOS podfile
5. point to the WordPressAuthenticator development pod (`pod 'WordPressAuthenticator', :path => '/your/path/to/WPAuth'`
6. `pod install`
7. run WCiOS
8. verify the subheadline buttons remain purple (see list of button titles below)
9. attempt to paste some text into the password field the "Paste" tooltip …

Configure subheadline button title color

---

WordPressAuthenticator.podspec

Update the podspec file so a new v1.0.5 release can be made.

Update WordPressAuthenticator to Mark 1.0.5

---

WordPressAuthenticator/Signin/Login2FAViewController.swift

This PR exposes the method `handleTextFieldDidChange`, so that:
A. It matches the Storyboard Signature (incoming parameter)
B. It's exposed to ObjC
Ref. [WPiOS Issue #9979](https://github.com/wordpress-mobile/WordPress-iOS/pull/9979)
cc @frosty @jklausa  (Thank you  two!!!)
Please refer to [this WP issue for testing steps](https://github.com/wordpress-mobile/WordPress-iOS/pull/9979)

iOS 12 Beta 6: Fixing Autofill Crash

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Extensions/String+Underline.swift
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/NUX/NUXButton.swift
WordPressAuthenticator/NUX/NUXButtonViewController.swift
WordPressAuthenticator/NUX/NUXKeyboardResponder.swift
WordPressAuthenticator/NUX/NUXLinkMailViewController.swift
WordPressAuthenticator/NUX/WPHelpIndicatorView.swift
WordPressAuthenticator/Signin/Login2FAViewController.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift
WordPressAuthenticator/Signin/LoginProloguePageViewController.swift
WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
WordPressAuthenticator/Signin/LoginWPComViewController.swift
WordPressAuthenticator/Signup/SignupEmailViewController.swift

Migration to Swift 4.2 and updated dependencies to the rest of the internal pods already migrated

Migration to Swift 4.2

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

In reference to [this change](https://github.com/wordpress-mobile/WordPress-iOS/pull/10210), this PR  relaxes dependencies expressed against both `WordPressKit` & `WordPressShared`.
The `.podspec` has also been updated to accommodate the next minor version.

Relaxed version dependencies on both WordPressShared and WordPressKit

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

With the update to `WordPressShared` & `WordPressKit`, we also need to increment this dependency.
After running `pod install --repo-update` locally, the branch should build and tests should pass.

Bump upstream dependencies

---

WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayText.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorDisplayTextTests.swift

Fixes #35. Ref. https://github.com/woocommerce/woocommerce-ios/issues/472.
**Background**
Some of the login text that displays to the user has instructions that are WordPress focused. It can be confusing to a user when the host app is WooCommerce instead. 
**Summary**
In this PR, we're exposing the instructions label and allowing the text to be overridden on init. The default display text remains the same for WordPress users. The `WordPressAuthenticatorDisplayText` struct is introduced as a way to manage any text that displays directly to the user. 
Better names welcomed! I tried: UserMessages, UIText, and TextOverrides. None of them quite fit.
**To Test (Pick one) - WCiOS Option**
1. Check out this PR and run it: https://github.com/woocommerce/woocommerce-ios/pull/487#event-2005399244 …

Add the ability to override text displayed to the user

---

WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Signin/LoginWPComViewController.swift

Fixes #40
Corresponding WPiOS PR is https://github.com/wordpress-mobile/WordPress-iOS/pull/10783
Password autofill may enter usernames instead of email, as there is no concrete way to tell iOS to prefer email over usernames when both are available. To deal with that possibility, an invisible password field has been added that can only be filled by password autofill. When it gets a value, login is attempted immediately.

Add support for password autofill during login

---

.circleci/config.yml
Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/xcshareddata/xcschemes/WordPressAuthenticator.xcscheme
WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorDisplayTextTests.swift

Uses CircleCI to validate that everything is working correctly.
Also fixes issues causing the builds to fail

Add automated testing

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

Propagates the fix for [this issue](
https://github.com/wordpress-mobile/WordPressKit-iOS/pull/80) in `WordPressKit` to `WordPressAuthenticator`, en route to WPiOS.
Checkout the branch and confirm that existing tests pass.

Updated podspec and Podfile to reflect WordPressKit revision

---

WordPressAuthenticator.podspec

In the [preceding PR](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/49/), I omitted the beta suffix from the version in the podspec

Corrected podspec version number

---

.circleci/config.yml
Gemfile

This is a small CircleCI config update that ensures the specs repo is up to date before validating the podspec. Without this change, CI could fail to find recently updated pods.
@stevebaranski This fixes the failure you encountered in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/50

CircleCI: Update specs repo before validating podspec

---

WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
WordPressAuthenticator/Signin/LoginWPComViewController.swift
WordPressAuthenticator/Signup/SignupEmailViewController.swift

This PR updates duplicate accessibility identifiers ("Email address", "Log In Button", and "Next Button") to unique values. This ensures that during UI testing we're targeting the correct element.
Corresponding WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/10987

Update accessibility identifiers to unique values

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Services/WordPressComBlogService.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

And handle accordingly.
Fix: #52 
If fetchSiteInfo fails due to privacy we call a new method that utilizes the call for connect/site-info.
If this call returns successfully we check if the user is already logged in with a WPCom site and if they are we show the alert to logout.

Check if fetchSiteInfo fails due to authorization required (private)

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Services/SignupService.swift

Supports the resolution of [this issue](https://github.com/wordpress-mobile/WordPressKit-iOS/issues/86) in `WordPressKit`.
I've designated this a Draft PR, unless or until the associated update to [`WordPressKit`](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/103) has been properly versioned.
To test:
- Branch should build.
- Tests should pass.
Update release notes:

Updated WordPressAuthenticator to absorb latest changes to WordPressKit

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj

Update pod spec to point to more flexible version of Lumberjack and updated version of WordPressKit.

Update to version 1.1.11

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj

This relaxes how we pin WPKit dependency, so it's easier to work with in WPiOS. Also includes artifacts of running `bundle exec pod install`.

Relaxed podfile pinning

---

.circleci/config.yml
Gemfile.lock
Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Extensions/UIImage+Assets.swift
WordPressAuthenticator/NUX/NUXButtonView.storyboard
WordPressAuthenticator/NUX/NUXButtonViewController.swift
WordPressAuthenticator/Signin/EmailMagicLink.storyboard
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginProloguePromoViewController.swift
WordPressAuthenticator/Signup/Signup.storyboard
WordPressAuthenticator/UI/SearchTableViewCell.xib

This change fixes compatibility with recent versions of CocoaPods. Once merged it will be possible to update CocoaPods in all of our projects.
The issue we are seeing is caused by [`GoogleSignInRepacked`](https://github.com/wordpress-mobile/GoogleSignInRepacked). It seems that it is not behaving as a true dynamic framework and some linking changes by CocoaPods mean it doesn't work anymore. The issue is described [here](https://github.com/CocoaPods/CocoaPods/issues/8612#issuecomment-477219241).
The solution is to use the official `GoogleSignIn` pod and add `s.static_framework = true` to the podspec.
Changing to a static framework means that everything gets added to the main bundle. This can lead to conflicts once it is installed in an app. I have made a few changes to mitigate this:
- The …

Fix compatibility with recent versions of CocoaPods (> 1.5.3)

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Extensions/UIImage+Assets.swift
WordPressAuthenticator/NUX/NUXButtonViewController.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginProloguePromoViewController.swift

In https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/67, as part of converting to a static framework, I moved images and assets to `WordPressAuthenticatorResources.bundle`. `.storyboard` and `.xib` files remained in the main bundle.
This mostly worked fine for WordPress-iOS, but has proved to be problematic in some cases there and in all cases for WooCommerce-iOS. Image references in storyboards were not resoving, with errors like this:
```
2018-12-11 09:21:31.650079-0800 WordPress[91387:1155878] Could not load the "beveled-blue-button-down" image referenced from a nib in the bundle with identifier "org.cocoapods.WordPressAuthenticator"
``` 
Fixes https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/38.
The solution I have implemented is as follows:
- …

Add storyboards and xibs to the resource_bundle

---

.circleci/config.yml
Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/NUX/NUXSegueHandler.swift
WordPressAuthenticator/Services/WordPressXMLRPCAPIFacade.m

Following https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/67 and https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/68, this PR fixes compatibility with Xcode 10.2 and updates CircleCI to use it. Xcode 10.1 will still work fine.

 Xcode 10.2 compatibility

---

WordPressAuthenticator/NUX/NUXButtonView.storyboard

Fixes #38.
`beveled-blue-button-down` is an image that exists in WordPress-iOS, likely left over from the extraction from there. It is not used by WordPressAutheticator since backgrounds are [set in code](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/develop/WordPressAuthenticator/NUX/NUXButton.swift#L96).
This removes the erroneous references to fix the console warning.

NUXButtonView.storyboard: Remove references to beveled-blue-button-down

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

_WordPressKit_ has been updated to the [major version](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/145) 4.0.0-beta.
This PR update the podspec and WordPressKit versions.
I also updatetd the Podfile and run a bundle exec pod install.

Update WordPressKit version

---

WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift

This makes the `bundle` var in `WordPressAuthenticator` public so that the bundle can be accessed from outside the framework.
This will allow https://github.com/wordpress-mobile/WordPress-iOS/issues/11444 to be fixed.

Make WordPressAuthenticator.bundle public

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift

Merge Release/1.3.1 into master.
1.3.1 is a patch version that includes the changes from https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/78.

Merge Release/1.3.1 into master

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

This updates WordPressKit to the latest version.
To test:
Build and test. Verify tests pass.

Updating WPKit pod version.

---

WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Private/WPAuthenticator-Swift.h
WordPressAuthenticator/Services/LoginFacade.m
WordPressAuthenticator/Services/WordPressComOAuthClientFacade.m
WordPressAuthenticator/Services/WordPressXMLRPCAPIFacade.m
WordPressAuthenticator/Signup/SignupGoogleViewController.swift
WordPressAuthenticatorTests/Services/LoginFacadeTests.m

This makes the changes needed for the WordPressAuthenticator pod to be installed as a static or dynamic framework (with or without `use_frameworks!`). Currently, it does not work correctly when installed statically. Even though `static_framework` is set to true, these changes are needed to ensure it works without `use_frameworks!`.
The changes are as follows:
- Use `#import "WPKit-Swift.h` instead of `#import <WordPressKit/WordPressKit-Swift.h>` to avoid the issue described in https://github.com/CocoaPods/CocoaPods/issues/7594.
You can see that the tests still build and pass with the changes I've made.
Related to https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/203 and https://github.com/wordpress-mobile/WordPressKit-iOS/pull/151

Compatibility with both CocoaPods dynamic and static frameworks

---

WordPressAuthenticator.podspec

Bitcode is disabled in the `.podspec` due to a previous incompatibility. I have tested it out and it works fine now, so we can re-enable it.

Enable Bitcode

---

Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

This PR removes a Jetpack error override we were using, that [seemed to cause quite some confusion for our users and HEs](https://github.com/wordpress-mobile/WordPress-iOS/issues/11505).
This PR does not aim to improve the error messaging in general, just to remove the override that was forcing the lib to show the Jetpack errors instead of letting the real errors be shown.
This PR can be tested through this WPiOS branch: `issue/11505-remove-jetpack-error`
1. Run WPiOS and login in by site address.
2. Enter `therealnews.altervista.org` in the site address.
You should see the following error message:

Removes the Jetpack error override.

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Services/WordPressComOAuthClientFacade+Swift.swift
WordPressAuthenticator/Services/WordPressComOAuthClientFacade.m

I recently made changes to WordPressKit to allow WP.com urls to be configured for testing purposes (https://github.com/wordpress-mobile/WordPressKit-iOS/pull/141). This is the corresponding changes to WordPressAuthenticator to take advantage of that.
I have added two new items to `WordPressAuthenticatorConfiguration`: `wpcomBaseURL` and `wpcomAPIBaseURL`. They default to the correct values so that existing installations will not break.
I have also updated the `.podspec` version since this includes API changes.
- All tests pass and the podspec validates.
- (Optional) Check out my corresponding WPiOS branch (`try/configure-base-urls`) and do a smoke test of the login flow. Draft PR is here: https://github.com/wordpress-mobile/WordPress-iOS/pull/11655.

Make WordPress.com URLs configurable through WordPressAuthenticatorConfiguration

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXLinkMailViewController.swift
WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift

Adds three new accessibility identifiers for use in UI tests (to support running tests with the device UI set to any language).
To test:
* Build the project and confirm the unit tests pass.
* Optional: Try out the draft PR integrating these changes with the WPiOS UI tests (https://github.com/wordpress-mobile/WordPress-iOS/pull/11665 - test steps in that PR).

Add accessibility identifiers for UI tests

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

* This PR updated `WordPressShared` dependency to the latest version `1.8.0-beta.1` (https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/204), and updated its own pod version to `1.5.0-beta.3`.

Update `WordPressShared` pod version

---

WordPressAuthenticator/Services/SignupService.swift
WordPressAuthenticator/Services/WordPressComAccountService.swift
WordPressAuthenticator/Services/WordPressComBlogService.swift
WordPressAuthenticator/Signup/SignupEmailViewController.swift

As I have been developing networking mocking, I have discovered a few places that the WP.com API URL needs to be injected which I missed in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/93.
This PR makes sure every instance of `WordPressComRestApi` in WordPressAutheticator uses the injectable `wpcomAPIBaseURL`.

Use wpcomAPIBaseURL in all WordPressComRestApi instances

---

WordPressAuthenticator/Model/WordPressComSiteInfo.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

Self hosted sites that have jet pack return with a successful response from the fetch site so we don't show the "logout" prompt for those sites.
**Before**:
**After**:

Allowing to continue login flow for self hosted sites that have Jetpack.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/NUX/NUXButtonView.storyboard
WordPressAuthenticator/Signin/EmailMagicLink.storyboard
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signup/Signup.storyboard
WordPressAuthenticator/UI/SearchTableViewCell.xib

This change ensures that the crash that occurred in https://github.com/wordpress-mobile/WordPress-iOS/issues/11848 cannot happen for WordPressAuthenticator.
Apart from the small bundle rename from `WordPressAuthenticator.bundle` to `WordPressAuthenticatorResources.bundle`, all the storyboards and xibs have been updated to load from the correct module. This won't be needed once CocoaPods 1.8 is released (see https://github.com/CocoaPods/CocoaPods/pull/8890).
@jkmassel Since we are not encountering the crash in WPAuthenticator, we could not make this change and wait for the CocoaPods update to land. What do you think?

Rename WordPressAuthenticator.bundle to WordPressAuthenticatorResources.bundle to avoid conflicts

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXButtonViewController.swift
WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift

Adds accessibility identifiers to the prologue screen needed for signup flow UI tests (see https://github.com/wordpress-mobile/WordPress-iOS/pull/11931). Also adds more options for setting accessibility identifiers to UI buttons.
In the future we may want to improve how accessibility identifiers are set on buttons, to avoid/prevent using localized strings (since these identifiers are not exposed to users and should be the same regardless of UI language, for use in tests). However, the change in this PR will make it possible to set the necessary identifiers for existing tests with minimal changes to existing buttons.
To test:
* Follow the test steps in wordpress-mobile/WordPress-iOS#11931 to test these changes in the WordPress iOS tests.

Add accessibility identifiers needed for UI tests

---

WordPressAuthenticator/NUX/NUXLinkAuthViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signup/SignupGoogleViewController.swift

First step to implement [this request](https://github.com/wordpress-mobile/WordPress-iOS/issues/11893).
Since we're only adding comments, we only need to check the code still compiles.
1. Check out WPiOS branch `issue/11893-add-comments-for-critical-path`.
2. Reinstall the pods.
3. Make sure the project builds correctly.

Documents some critical stats we're tracking.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signup/SignupEmailViewController.swift

This method will be removed from the Shared pod.
See https://github.com/wordpress-mobile/WordPress-iOS/pull/11967

Remove unused call to WPStyleGuide.configureColors

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/NUX/NUXLinkMailViewController.swift
WordPressAuthenticator/NUX/WPWalkthroughTextField.h
WordPressAuthenticator/NUX/WPWalkthroughTextField.m
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginLinkRequestViewController.swift
WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
WordPressAuthenticator/Signin/LoginSocialErrorCell.swift
WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Signin/LoginWPComViewController.swift
WordPressAuthenticator/UI/LoginTextField.swift
WordPressAuthenticator/UI/SearchTableViewCell.swift
WordPressAuthenticator/UI/SiteInfoHeaderView.swift

To finish my efforts to use the new WPiOS color scheme during login, this PR makes the remaining colors from the old WPiOS color palette configurable. It also removes the default `WordPressAuthenticatorStyle`, and makes the `style` argument mandatory.
This will have compatibility implications for the other projects that use this pod.

Make remaining colors configurable

---

WordPressAuthenticator/Model/WordPressComSiteInfo.swift

Fixes https://github.com/woocommerce/woocommerce-ios/issues/1113
- WCiOS PR branch for testing: https://github.com/woocommerce/woocommerce-ios/pull/1118
- WPiOS PR branch for testing: https://github.com/wordpress-mobile/WordPress-iOS/pull/12170
In [this PR](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/98/files), we switched the API call to fetch site info during site address sign in flow from `fetchSiteInfo` to `fetchUnauthenticatedSiteInfoForAddress` in order to accommodate both public and private sites (`fetchSiteInfo` only works for public sites). However, the responses from these two calls are very different.
With `fetchSiteInfo` (what we called before for WP.com sites), the response is like:
```
{
"ID": 161199960,
"name": "fun testing",
"description": "", …
```

`WordPressComSiteInfo`: update setting `hasJetpack` from remote response

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift

This adds a new Log In flow. Namely, if `showNewLoginFlow` is `true`, when Log In is selected a button view now appears with available options.
This can be tested with WPiOS PR https://github.com/wordpress-mobile/WordPress-iOS/pull/12305.

Log In: show button view with login options.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

This change allows displaying a login options button view after a site address has been validated. As this change is specifically for Woo, it should be tested with the Woo app.
(Related discussion can be found [here](https://wp.me/pauD4L-li-p2/#comment-268).)
**Disclaimers**: 
- Woo has not adopted the latest WPAuth pod, and there are several colors `WordPressAuthenticatorStyle` now requires. I picked some to get it working, but they're obviously incorrect. Please ignore the colors in these examples as this PR is specific to the flow, and I assume those colors will be set correctly when Woo updates WPAuth.
- This change assumes in the future Woo will start the login process from the site address view. So there have been no changes to the initial login view (i.e. the email entry).
--- …

Log In: show login options after site address validated.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

If the following conditions are met, a 'Continue with Apple' button is added to the Log In options button view.
- Is Xcode 11.
- Is iOS 13.
- The `WordPressAuthenticatorConfiguration:enableSignInWithApple` flag is `true`.
Since there is no button action just yet, tapping the SIWA button will result in:
- The button view being dismissed.
- Log messages in the console. Ex: `Login Prologue: Apple tapped.`
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12334

[SIWA] Log In: add 'Continue with Apple' button to login options

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginNavigationController.swift

Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/12211.
In iOS 13 the default modal presentation style changes to `UIModalPresentationAutomatic`, which resolves as `pageSheet`. This results in the login views being dismissible. I've updated this to `fullScreen`, restoring the previous behaviour.
Please check out the WPiOS branch at https://github.com/wordpress-mobile/WordPress-iOS/pull/12335 to test this PR.

Fix iOS 13 presentation style.

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/Signin/AppleAuthenticator.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

When the 'Continue with Apple' button is tapped, the 'Sign In with Apple' process is initiated, requesting the Apple ID information from the user.
Once credentials have been entered, the flow currently returns to the prologue view as account creation is not yet implemented. The user's email and full name will be logged in the console. Ex:
```
Apple Authenticator credentials: Optional("useremail@gmail.com"), Optional(givenName: First familyName: Last )
```
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12336

[SIWA] Request Apple credentials

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Services/SignupService.swift
WordPressAuthenticator/Signin/AppleAuthenticator.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

Related WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/181
This adds methods to create a WordPress account by sending Apple ID credentials to the method added in the above WPKit PR.
This can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12350

[SIWA] Add methods to create WP account

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Model/LoginFields.swift
WordPressAuthenticator/Services/SocialService.swift
WordPressAuthenticator/Services/WordPressComAccountService.swift
WordPressAuthenticator/Signin/AppleAuthenticator.swift
WordPressAuthenticator/Signin/LoginViewController.swift

This adds logic to show the account created epilogue after a WP account is created with an Apple ID. To note, the endpoint doesn't yet support Apple, so account creation will fail, thus the epilogue won't actually show yet.
This also passes Apple specific parameters to the social connect endpoint in WPKit, although it's not used yet.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12360
Ref WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/182

[SIWA] Show new account epilogue

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/AppleAuthenticator.swift

Just a small tweak to decode the SIWA identity token before we use it, instead of using just the base64 representation.
**To test**
* Use this branch with WPiOS and try to Sign in with Apple. Without this change, you'd get an error:
```
2019-08-23 16:21:26:757 WordPress[47394:19742393] Apple Authenticator: signup failed. error: Error Domain=WordPressKit.WordPressComRestApiError Code=7 "Invalid authentication token (JWT)." UserInfo={WordPressComRestApiErrorMessageKey=Invalid authentication token (JWT)., NSLocalizedDescription=Invalid authentication token (JWT)., WordPressComRestApiErrorCodeKey=jwt-authentication}
```
With this change, you won't get that error (you'll get a different one, but we'll hopefully fix that soon too!)

Apple Sign In: Decode identity token to string

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/AppleAuthenticator.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
WordPressAuthenticator/Signin/LoginWPComViewController.swift

After selecting an Apple ID, if there is already a WP account associated with the email, the WP password entry view is now displayed.
If account creation doesn't work yet, to test this you can call `logInInstead()` in the account creation failure block in `AppleAuthenticator`.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12383
Also, you may see a slew of errors related to `Login.storyboard`. Those predate these changes.

[SIWA] Redirect to WP password entry of using associated email

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/NUX/WPWalkthroughTextField.m
WordPressAuthenticator/UI/LoginTextField.swift

Refs #12320. This PR implements some improvements to the appearance of the login flow for dark mode.
For full description and testing steps, see https://github.com/wordpress-mobile/WordPress-iOS/pull/12386. These PRs should be tested together.

Dark mode improvements

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/NUX/NUXButton.swift
WordPressAuthenticator/Signin/LoginSocialErrorCell.swift

Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/12320.
This PR fixes some dark mode issues with the authenticator:
* The terms and conditions text when you tap sign in is now easier to read and a better size.
* The Next button now shows a white loading indicator in dark mode.
* The username instruction cell used in WPiOS now has a better text color.
**To test**
* You can use this branch of WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/create?base=wordpress-mobile%3Arelease%2F13.2&head=wordpress-mobile%3Afix%2Fnux-epilogue-dark-mode
* Do a fresh install of the app and tap Sign up. Check you can read the terms and conditions text.
* Sign up a new account and check the epilogue looks okay (these changes are in the WPiOS branch).
* When logged in, navigate to Me …

Dark mode: text and button fixes

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift

Refs. [WP iOS #12447](https://github.com/wordpress-mobile/WordPress-iOS/pull/12447)
This PR adds the SIWA _Continue with Apple_ button in the Sign Up buttons list
• Run [WP iOS #12447](https://github.com/wordpress-mobile/WordPress-iOS/pull/12447)

[SIWA] Add Continue with Apple to Sign Up

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressSupportSourceTag.swift
WordPressAuthenticator/Extensions/FancyAlertViewController+LoginError.swift
WordPressAuthenticator/Signin/AppleAuthenticator.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

Ref WPiOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/12442
When signing up / logging in with Apple and something goes wrong, an alert is now displayed.
- If Apple authentication fails, a generic `Apple authentication failed.` message is displayed.
- If the API fails, the alert will show the API specific error message.
**NOTE**: The alert now checks the `supportEnabled` state of the host app before adding the help link. If Zendesk is disabled in the host app (as it is in WPiOS, for example), the help link is not displayed. However, once ZD is enabled, the link will appear.
This can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12468

[SIWA] Show error alert when authentication fails

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/AppleAuthenticator.swift

Ref WPiOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/12434
The incorrect delegate method was being called with existing accounts. Now, if logging into an existing account, the `sync` method is called (instead of `createdWordPressComAccount`).
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12471

[SIWA] Sync account with host app for existing accounts

---

.circleci/config.yml
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/Signin/AppleAuthenticator.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

This removes all `#if XCODE11` checks and updates the CircleCI config to build with Xcode 11. It enables the code for Sign In With Apple.

Enable Xcode 11 for all builds

---

.circleci/config.yml

Adding a CircleCI job that will run `pod trunk push` on the podspec whenever the repo is tagged.

CircleCI: Add job for publishing podspec to trunk

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift

Reordering the sign in/sign up buttons to not have Apple be the first one seen by the user.
cc: @mattmiklic

Reordering the SIWA buttons to de-emphasize it

---

WordPressAuthenticator.podspec

This is a version bump for the SIWA release. Since Xcode 10 support was dropped in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/130, I have gone to 1.9.

Podspec: Bump version to 1.9.0-beta.1 for SIWA release

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/AppleAuthenticator.swift

WordPress-iOS branch to test: https://github.com/wordpress-mobile/WordPress-iOS/pull/12522
Adds a missing event to track signin with Sign in with Apple and several source parameters that did not include `apple`.

Adds missing signin events for SIWA

---

WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

To address wordpress-mobile/WordPress-iOS#12188
Test by logging out and then attempting to log in by using an invalid URL (such as %$#), error text should be "Please enter a complete website address, like example.com." and title text should be "Enter the address of the WordPress site you'd like to connect."

Change copy per Editorial and to reflect Android app

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDelegateProtocol.swift
WordPressAuthenticator/Signin/AppleAuthenticator.swift

Ref WPiOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/12399
This adds functionality:
- For host apps to check the state of an Apple User.
- Informs host apps with the Apple User when an Apple account has been successfully authenticated.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12549

[SIWA] Check Apple User state

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Signin/AppleAuthenticator.swift

Ref WPiOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/12535
This adds methods for the host apps to start/stop listening to Apple's `credentialRevokedNotification`. 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12552
(ping @ctarda )

[SIWA] Observe Apple Credential Revoked notification

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Signin/AppleAuthenticator.swift

Ref WPiOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/12399
This changes checking the Apple ID credential state:
- Instead of deciding if a credential is valid, simply send the state back to the host app.
- Instead of _immediately_ notifying the host app when an Apple account has been successfully authenticated, that call is now made is the `success` block of the `createWPComUserWithApple` call.
The main point here is to let the host app decide how to handle the `CredentialState`s.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12585
(ping @ctarda )

[SIWA] Send Apple credential state to host app

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXButton.swift

Fixes #140 
This PR reload the activity indicator color when the button `isEnabled` property is true/false
- Run WP iOS [#12610](https://github.com/wordpress-mobile/WordPress-iOS/pull/12610)

[Dark Mode] Update activity indicator color when button is disabled

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Services/SignupService.swift
WordPressAuthenticator/Signin/AppleAuthenticator.swift

Ref WPiOS issue #https://github.com/wordpress-mobile/WordPress-iOS/issues/12556
WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/183
This uses the changes in WPKit to capture the existing account's email address for display on the WP password entry view.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12606
(ping @ctarda )

[SIWA] Show email address on WP password entry view

---

.circleci/config.yml

This is just an Orb bump to used the improved CocoaPods publishing from https://github.com/wordpress-mobile/circleci-orbs/pull/38. It was already tested on that PR.

CircleCI: Use updated Orb to publish to trunk & post to Slack

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

Merge release/1.10.0 into Master

Merge release/1.10.0 into Master

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/AppleAuthenticator.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signup/SignupGoogleViewController.swift

This updates tracking signup and login for social accounts:
- To be consistent between Google and Apple (i.e. they track the same actions). 
- Adding ["source": "google"] to Google tracks to differentiate between the two.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12803

Consistently track Google and Apple sign up/log in actions

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/Login2FAViewController.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Signup/SignupGoogleViewController.swift

Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/12827. This PR adds `signedIn` tracks events everywhere we're already posting a `loginSocialSuccess` event. You can test this PR with the associated WPiOS PR here: https://github.com/wordpress-mobile/WordPress-iOS/pull/12981
I updated 4 locations where I could find usages of `loginSocialSuccess` with no associated `signedIn`. I'm not 100% sure if these are correct, so please let me know what you think! Here's my thoughts on each one:
* **Login2FAController**: I'm a little unsure about this one, as the line above mentions Google login but I'm honestly not quite sure how to trigger this method. It doesn't appear to get called by doing a normal sign in with 2FA.
* **LoginEmailViewController**: I updated this one, but as far as I …

Add signed_in Tracks event whenever we log in socially

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Signup/SignupGoogleViewController.swift

Ref WPiOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/13004
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13005
Woo test branch: `try/google_login`
This fixes the path where a user tries to login in with a Google account that has 2FA enabled on the WordPress account.
Previously, it was using the Google _sign up_ flow, which was incorrect (and doesn't handle 2FA accounts).
This moves the Google sign in logic into `LoginViewController` so it can be accessed via `LoginEmailViewController` (flow used by Woo) and `LoginPrologueViewController` (flow used by WPiOS).

Fix Google 2FA login

---

.circleci/config.yml
Podfile
Podfile.lock
README.md
WordPressAuthenticator.podspec
WordPressAuthenticator/Services/LoginFacade.h
WordPressAuthenticator/Services/LoginFacade.m
WordPressAuthenticator/Services/SignupService.swift
WordPressAuthenticator/Services/WordPressComOAuthClientFacade.h
WordPressAuthenticator/Services/WordPressComOAuthClientFacade.m
WordPressAuthenticator/Signin/AppleAuthenticator.swift
WordPressAuthenticator/Signin/Login2FAViewController.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift

WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/201
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13013
This adds support for logging in with an Apple account linked to a WordPress account that has 2FA enabled.
Can be tested with WPiOS PR noted above.

[SIWA] Add flow for 2FA accounts

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/Login2FAViewController.swift

I moved the color configuration for the `sendCodeButton` to a more appropriate function in `Login2FAViewController` in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/164/commits/2d6fd81ce79e2b6e21754e89004bf1c84d10de53, but forgot to call it in `viewWillAppear` 🤦🏻‍♀️
Example branch: [`issue/wcios-1555-color-updates`](https://github.com/wordpress-mobile/WordPress-iOS/compare/issue/wcios-1555-color-updates?expand=1)
- Launch the app
- Log in with WP.com with an account with 2FA enabled
- Enter the email address
- Enter the password --> should see the 2FA screen, and the "Text me a code instead" text button should have the right color
(there is a slight change in the blue color similar to https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/164)
before | …

Color update: style the send code button in `viewWillAppear` in `Login2FAViewController`

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/13062. This is a dependency of https://github.com/wordpress-mobile/WordPress-iOS/pull/13067. 
Before | After 
--------|-------
When opening the Login or Signup dialog, the first button is now selected by VoiceOver instead of the _Dismiss_ button.
I added support for dismissing the dialog using VoiceOver's escape gesture — making a Z with 2 fingers. 
1. Use the branch in https://github.com/wordpress-mobile/WordPress-iOS/pull/13067. 
2. Log out. 
3. Turn VoiceOver on.
3. Tap on the Login button.
5. Confirm that: 
a. The first selected (and announced) element is the first button and not the Dismiss button
b. You can dismiss dialog by using the VoiceOver escape gesture (Z)
1. Use the same WPiOS branch
2. Log out. 
3. Turn …

[VoiceOver] Login and Signup enhancements

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Logging/WPAuthenticatorLogging.h
WordPressAuthenticator/Logging/WPAuthenticatorLogging.m
WordPressAuthenticator/Private/WPAuthenticatorLoggingPrivate.h
WordPressAuthenticator/Private/WPAuthenticatorLoggingPrivate.m

Rather than using int as the type, we use DDLogLevel per https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/DynamicLogLevels.md.

Fix memory layout issues with DDLogLevel

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/NUX/WPWalkthroughTextField.m
WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift

This fixes the issues described in https://github.com/wordpress-mobile/WordPress-iOS/issues/13086. 
This is a dependency of https://github.com/wordpress-mobile/WordPress-iOS/pull/13099. This PR needs to be reviewed first. 
The changes mainly involve the `LoginSiteAddressViewController` and `LoginSelfHostedViewController`. 
For errors that happen after pressing _Next_, we sometimes use the [`errorLabel`](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/1361a86fec25f7b69d88f74a7bb676b739749713/WordPressAuthenticator/NUX/NUXViewController.swift#L56) to display the error. The problem with this is that it is a UI element that just appears unannounced. A VoiceOver user may not know that it's there and would expect that a network request is still happening in the background. …

[VoiceOver] Self-hosted Login Flow enhancements

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

Updates to latest WordPressKit ([4.5.6-beta.1](https://github.com/wordpress-mobile/WordPressKit-iOS/releases/tag/4.5.6-beta.1)).
Related WordPress-iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13198

Update WordPressKit to 4.5.6-beta.1

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift

This change does the following:
- Renames `showNewLoginFlow` to `showLoginOptions`.
- Adds `enableUnifiedAuth` in preparation for Unified Auth project.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13394

Auth init: login configs

---

WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Extensions/NSObject+Helpers.swift
WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
WordPressAuthenticator/Extensions/UIViewController+Helpers.swift
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Signup/Signup.storyboard
WordPressAuthenticator/Signup/SignupEmailViewController.swift

Master issue #182 - this is a spike to test removing segues.
This PR removes all references to the segue `.showEmailLogin` and programmatically navigates the user to the `LoginEmailViewController` screen. There are 3 areas where the segue has been removed: WPiOS sign up, WPiOS sign in, and WCiOS sign in.
2. Check out this branch for WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/tree/try/break-up-storyboard and point it to your local pod by changing the podfile location to your local copy of WordPressAuthenticator-iOS
3. Build the Authenticator project
4. `rake dependencies` on WPiOS
5. Build the WPiOS project. You are now set up with local pod development! 
6. Navigate to and back from each of these flows: 
1) Login > Continue with WordPress.com - …

Remove .showEmailLogin segue

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Signup/SignupEmailViewController.swift

Moves forward https://github.com/wordpress-mobile/WordPress-iOS/issues/13583
This PR improves the error handling in WPAuth so that we don't ignore some error responses.
WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/13585
WPKit: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/220
Once this is merged I'll open the WPiOS PR.
Try signing up with a valid email account.  It should send you the magic link.
Try signing up with an invalid email provider.  For example "tester@mailinator.com".
You should see an error prompting you to use a different email provider.
Try singing up with a used email address (you can try with the email of your existing account).
You should see an error letting you know the email address is not available.

Fix error handling for email verification.

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

This PR updates the podfile to point to the feature branch for WordPress kit. 
Authenticator needs updated at the same time as WPiOS, as they both depend upon `wpkit` and expect the same version to be used in WPiOS.
**Known issues**
CircleCI podspec changes are broken on purpose. It's currently failing because the `wpxmlrpc` dependency version 4.6.0-beta.1 hasn't been published to CocoaPods yet. It's set to that declaration so that running `rake dependencies` in Authenticator and WPiOS will pass.
**Do not merge this PR until:**
1. The `wpxmlrpc` pod changes have been merged to develop ✔️ 
2. The `wpxmlrpc` podspec has been published to CocoaPods ✔️ 
3. This podfile points to the correct version of wpkit (4.6.0-beta.1) ✔️ 
4. This podspec shows the `WordPressKit` dependency version …

Update WordPressKit pod to v4.6.0 beta.1

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

Integrates WPKit 4.6.0-beta.2 into the Authenticator.
WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/227
WPiOS Integration Branch: `try/integrate-wpkit-216-AtomicAuthenticationServiceRemote`
No testing needed, but if you want you can run `pod install` in the WPiOS integration branch to make sure all works fine.

Integrate WPKit 4.6.0-beta.2 into the Authenticator.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXButton.swift

Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/12441
This updates the NUX buttons when light/dark mode is toggled.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13636

Update NUX buttons when light/dark mode toggled.

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

This PR updates Authenticator to use the most recent version of WordPressKit. 
Ref. https://github.com/wordpress-mobile/WordPressKit-iOS/pull/232
**Do not merge until:**
- WordPressKit Swift 5 migration PR is merged first (above ref.) ✔️
- WordPressKit release has been published on CocoaPods ✔️
- this podfile has been updated to point to 4.6.0-beta.6 instead of a branch ✔️

Update version of WordPressKit to 4.6.0-beta.6

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift

Ref #https://github.com/wordpress-mobile/WordPress-iOS/issues/13441
This updates the style of the `Don't have an account?` button to match the log in by site address button.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13652

Update WP signup button style.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXLinkMailViewController.swift

Ref #https://github.com/wordpress-mobile/WordPress-iOS/issues/13664
This updates the Signup and Login Magic Link confirmation screen advising the user to check their spam/junk folder.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13665

Updating magic link instruction text.

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Signup/SignupEmailViewController.swift

Fixes a signup regression.  Existing accounts should be redirected to login, instead of displaying an error.
WPiOS: `try/fix-signup-issue`
WPKit: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/235
These tests are the same we did on the WPKit PR.  Since the code hasn't changed since that PR was tested, there may not be a need to re-check all 3 cases here.
1. Check out the WPiOS branch.
2. Install the pods.
3. Run the app from scratch.
4. Try to sign up with an existing account.
Verify that you're redirected to login and that you an complete the login process.
Same test steps as in Test 1, but try to sign up with a mailinator account instead (any random account will do, like `testing@mailinator.com`).
Verify that there's an error message explaining this email provider is not …

Fixed a SignUp regression.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/NUX/NUXButtonViewController.swift
WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift

Ref #https://github.com/wordpress-mobile/WordPress-iOS/issues/13620
This updates the appearance of the Google button shown in the login and signup flows.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13675

Update Google button appearance

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Services/OnePasswordFacade.swift

This PR updates 1PasswordExtension from 1.8.5 to 1.8.6, and migrates a small piece of code.
Ref. https://github.com/woocommerce/woocommerce-ios/issues/1929 
```
[IMPROVED] Moves all projects forward to Xcode 11 format
[IMPROVED] Updates build settings and localization targets
[IMPROVED] Converts swift projects to Swift 5
[IMPROVED] Moves the bar forward from iOS 7 to iOS 9
[IMPROVED] Removes all support for UIWebView <- ** this is what we are looking for **
[IMPROVED] Removes the deprecated call - (void)fillLoginIntoWebView:(nonnull id)webView forViewController:(nonnull UIViewController *)viewController sender:(nullable id)sender completion:(nonnull OnePasswordSuccessCompletionBlock)completion;
[FIXED] Updates Readme.md urls, removes mention of a newsletter
[FIXED] Updated …
```

Updated 1PasswordExtension to a version that removes the support for UIWebView

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/NUX/WPWalkthroughTextField.m
WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift

This PR updates the authenticator library to use the new Gridicons 1.0 framework. I've updated the podspec and Podfile (which I'll further update once the pod is released), as well as switched over to the new style method calls.
**To Test**
Build and run the associated WordPress-iOS PR, and ensure that the auth flow loads and that some of the icons loaded here appear correctly: https://github.com/wordpress-mobile/WordPress-iOS/pull/13682

Update to Gridicons 1.0

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Extensions/NSObject+Helpers.swift
WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
WordPressAuthenticator/Extensions/UIViewController+Helpers.swift
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Signup/Signup.storyboard
WordPressAuthenticator/Signup/SignupEmailViewController.swift

Fixes #205
Ref. #182  
This PR removes all references to the segue `.showEmailLogin` and programmatically navigates the user to the `LoginEmailViewController`. There are 3 areas where the segues have been removed: 
1. WPiOS sign up
2. WPiOS sign in
3. WCiOS sign in
2. `bundle exec pod install` and ensure there are no errors
4. Visit the WPiOS PR to run the changes: https://github.com/wordpress-mobile/WordPress-iOS/pull/13669
2. `bundle exec pod install`
4. Visit the WCiOS PR to run the changes: https://github.com/woocommerce/woocommerce-ios/pull/2007

Remove segue .showLoginEmail

---

WordPressAuthenticator.podspec

I'm just bumping the dependency of WordPressKit to 1.7.0-beta.1 to get at the same requirement as the main app on this PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13020

Update WordpressKit dependency to 1.7.0-beta.1

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/NUX/NUXButton.swift

Fixes #220 
Fixes accidental revert of #216 
This PR alters the "Continue with Google" string. It substitutes unicode non-breaking spaces (instead of keyboard spaces) to keep whitespace fidelity. It also helps the spaces stand out in the code so they aren't accidentally deleted or refactored by Xcode during a "format code" command (Ctrl + i).
The spaces are removed from the localized string so that translators can accurately translate it without worrying about the formatting.
Check out WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13730

Remove whitespace from translation string

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift

Fixes #224 
Ref. #182 
This PR removes all references to the segue `.showSignupMethod` and programmatically navigates the user to the `LoginPrologueSignupMethodViewController`. There are 2 areas where the segues have been removed:
1. WPiOS sign up
2. WPiOS sign in
4. Visit the WPiOS PR to run the changes: https://github.com/wordpress-mobile/WordPress-iOS/pull/13733

UL&S: Remove `.showSignupMethod`

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginViewController.swift

Fixes #227 
Ref. #182 
This PR removes all references to the segue `.show2FA` and programmatically navigates the user to the `Login2FAViewController`. There are 2 areas where the segues have been removed:
1. WPiOS login
2. WCiOS login
4. Visit the WPiOS PR to run the changes: https://github.com/wordpress-mobile/WordPress-iOS/pull/13786
4. Visit the WCiOS PR to run the changes: https://github.com/woocommerce/woocommerce-ios/pull/2071

UL&S: Remove `.show2FA`

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginEmailViewController.swift

Fixes #233 
This PR fixes the black screen bug. 
PR to test on WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/13827
After the Jetpack install flow, the user is asked to sign in again. The LoginEmailViewController is presented, and there text and a link below the email field that says, "Don't have an account? Sign up"
Tapping the "Sign up" link pushes the 3 button view instead of presenting the 3 button view. Pushing the nav creates the black screen (seen in Figure 2 below).
1. Have a self-hosted site that doesn't have Jetpack connected. (This also works if you go to the site, Jetpack > and scroll to the bottom to find the "Disconnect" button and click it.)
2. Log out of the WPiOS app if you are logged in.
3. Log into the app through the self-hosted flow: Login > enter site …

Jetpack Signup Flow pushes 3 buttons instead of present

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signup/Signup.storyboard

Fixes #229 
Ref. #182 
This PR removes all references to the segue `.showSigninV2` and programmatically navigates the user to the `SignupEmailViewController`. There is 1 area where the segue has been removed:
1. WPiOS signup
4. Visit the WPiOS PR to run the changes: https://github.com/wordpress-mobile/WordPress-iOS/pull/13828

UL&S: Remove `.showSigninV2`

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

Fixes #239 
Ref #182 
This PR removes all references to the segue `.showURLUsernamePassword` and programmatically navigates the user to the `LoginSelfHostedViewController`. There is 1 area where the segue has been removed:
1. WPiOS login
(Note that WCiOS doesn't use this specific segue. Theirs is coming next.)
4. Visit the WPiOS PR to run the changes: https://github.com/wordpress-mobile/WordPress-iOS/pull/13896

UL&S: Remove `showURLUsernamePassword` 

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginViewController.swift

Fixes #241 
Ref #182 
This PR removes all references to the segue `.showSelfHostedLogin` and uses a navController to navigate the user to the `SelfHostedLoginViewController`. There are 2 areas where the segue has been removed:
1. WPiOS login
2. WCiOS login
4. Visit the WPiOS PR to run the changes: https://github.com/wordpress-mobile/WordPress-iOS/pull/13904
4. Visit the WCiOS PR to run the changes: https://github.com/woocommerce/woocommerce-ios/pull/2143

UL&S: Remove .showSelfHostedLogin

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

With https://github.com/wordpress-mobile/WordPressKit-iOS/pull/241 the WPKit pod version was incremented. WPiOS failed to build because WPAuth depends on WPKit as well. So this simply updates WPKit pod version to make everyone happy!
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13917
Note the `Validate Podspec` test will continue to fail until there is an official WPKit release. I'll update that before merging. But you should be able to test locally successfully.

Updating WPKit version

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

Fixes #244 
Ref #182 
This PR removes all references to the segue `.showWPUsernamePassword` and programmatically navigates the user to the `LoginUsernamePasswordViewController`. There is 1 area where the segue has been removed:
1. WCiOS login
(No, WPiOS doesn't use this specific segue.)
4. Visit the WCiOS PR to run the changes: https://github.com/woocommerce/woocommerce-ios/pull/2151

UL&S: Remove .showWPUsernamePassword

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/WPWalkthroughTextField.m

Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/13939
This updates the secure text entry button whenever the `showSecureTextEntryToggle` flag is set. 
Previously, the button would only update initially, when the xib was loaded. This change allows the icon to be set after the initial load.
Specifically, for the WPiOS Signup Epilogue:
Can tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13973

Secure text entry button: Update when value is set.

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginEmailViewController.swift

Fixes #255  
Ref #182 
This PR removes all references to the segue `.startMagicLinkFlow` and programmatically navigates the user to the `LoginLinkViewController`. There are 2 areas where the segue has been removed:
1. WPiOS login
2. WCiOS login
4. Visit the WPiOS PR to run the changes: https://github.com/wordpress-mobile/WordPress-iOS/pull/14003
4. Visit the WCiOS PR to run the changes: https://github.com/woocommerce/woocommerce-ios/pull/2201

UL&S: Remove .startMagicLinkFlow segue

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

Release is set to 1.15-beta.5 to avoid conflicting with PR #260
Test with WordPress-iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13969

Uses WordPressUI 1.6.0-beta.1

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift

Fixes #259 
Ref. #182 
This PR removes the case `showDomains` that is declared in the `SegueIdentifiers` enum and was not used in any of the host apps nor the Authenticator classes. 
I'm unsure how to test this other than doing a search for `showDomains` in each of the host apps (which returns only a result for NUXViewController).
2. `bundle exec pod install` and ensure there are no errors
3. Check out this branch
4. Build and run (there should be no errors)
5. Check out the `develop` branch of WPiOS 
6. Set WPiOS to point to local pod dev for Authenticator
7. Build and run
8. ???
9. Profit!

UL&S: Remove .showDomains

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift

Fixes #262
Ref. #182 
This PR removes the case `showCreateSite` that is declared in the `SegueIdentifiers` enum and was not used in any of the host apps nor the Authenticator classes. 
I'm unsure how to test this other than doing a search for `showCreateSite` in each of the host apps (which returns only a result for NUXViewController).

UL&S: Remove .showCreateSite segue

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard

Fixes #264 
Ref. #182 
Remove the `showSignupEmail` case from the `SegueIdentifiers` enum. Programmatically navigate to the `SignupEmailViewController` in the `Signup.storyboard`. 
This case is used in 1 area:
1. WPiOS signup, after a successful Jetpack Install flow.
2. `bundle exec pod install`
3. Build the project
4. Check out the `develop` branch of WPiOS
5. Point to the local pod develop in WPiOS podfile
6. `rake dependencies`
7. Build and run
1. Have a self-hosted site that is disconnected from Jetpack (or was never connected in the first place, both work).
2. Log in using the self-hosted flow.
3. Go to the Notifications tab.
4. Go through the Jetpack Install flow. 
5. After successfully installing Jetpack, you'll be asked to Login or Signup. Choose the `Sign …

UL&S: Remove .showSignupEmail segue

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift

Fixes: #257 
This removes the `showUsernames` segue name, which was used in WPiOS Signup Epilogue. 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14048

Remove showUsernames segue name.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/WPWalkthroughTextField.h
WordPressAuthenticator/NUX/WPWalkthroughTextField.m
WordPressAuthenticator/UI/LoginTextField.swift

Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/13939
This change sets the secure text image color to either:
- The `placeholderColor` from `WordPressAuthenticatorStyle` if provided.
- The original color (i.e. `greyLighten10`).
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14049

Secure text image: use placeholder color if provided.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

Closes #270 
Ref. #182 
This PR removes all references to the segue `.showLoginMethod` and programmatically navigates the user to the 3 button view. There are 2 host apps where the segue has been removed:
1. WPiOS logins
2. WCiOS login
2. `bundle exec pod install` and ensure there are no errors
3. Build (there should be no errors)
4. Visit the WPiOS PR to run the changes: https://github.com/wordpress-mobile/WordPress-iOS/pull/14057
2. `bundle exec pod install` and ensure there are no errors
3. Build (there should be no errors)
4. Visit the WCiOS PR to run the changes: https://github.com/woocommerce/woocommerce-ios/pull/2244

UL&S: Remove .showLoginMethod

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

With https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/112/, the ability to show the login options button view from the Site Address view was added because it was expected Woo would utilize it. However, Woo never transitioned to this flow, and now the code is unused. In addition, the new [Unified Auth](https://wp.me/p91TBi-2F7) login flows differ, so it will never be used.
This change removes that code.
To test:
Since `showLoginOptionsFromSiteAddress` was never adopted by any host app, there is no change. So just verify log in by site address works as expected.
- In Woo and/or WordPress, change Podfile's Auth to point to this branch.
- When logging in, select log in by site address.
- After entering a valid site address, verify the Username/Password view is displayed.
| …

Remove support for `showLoginOptionsFromSiteAddress`.

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

Update develop with the latest WordPressUI 1.7.0
This should is the same change as the 1.16.1 release: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/278

1.17.0-beta.2 - Update WordPressUI to 1.7.0

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Signin/GoogleAuthenticator.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift

Ref #282 
This moves the code related to Google login to a new `GoogleAuthenticator` class. This replicates the logic previously in `LoginPrologueViewController` + `LoginViewController`. The intent is to remove the dependency on `LoginViewController`, and let the individual initiating VCs handle the login.
Previously, `LoginPrologueViewController` would call `loginFacade:loginToWordPressDotComWithSocialIDToken` to initiate WP login. It would catch the resulting Google login status, and simply call associated methods in `LoginViewController`. `LoginViewController` would then update the UI accordingly.
Now, `GoogleAuthenticator` calls `loginFacade:loginToWordPressDotComWithSocialIDToken`. It catches the resulting Google login status, and calls delegate methods in …

Refactor Google login logic

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/GoogleAuthenticator.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift

Ref #282 
https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/284 refactored the Google login logic into `GoogleAuthenticator`. 
This change:
- Updates `LoginEmailViewController` to use `GoogleAuthenticator` instead of `LoginViewController` for the Google login logic.
- Removes the Google login methods from `LoginViewController`, and updates `LoginEmailViewController` to handle Google login responses itself.
Can be tested with WCiOS PR: https://github.com/woocommerce/woocommerce-ios/pull/2341

Use refactored Google login from email entry view

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/GoogleAuthenticator.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signup/SignupGoogleViewController.swift

Ref #282 
This moves the Google Signup logic out of `SignupGoogleViewController` and into `GoogleAuthenticator`. `SignupGoogleViewController` is notified of Google's progress via `GoogleAuthenticatorSignupDelegate` methods.
Regarding the `GoogleAuthenticator` delegates:
Because `AuthenticatorCredentials` is a Swift `struct`, it isn't visible to ObjC. Therefore, I couldn't use one delegate protocol with optional methods. So I created two protocols, containing their own required methods. `GoogleAuthenticatorDelegate` has become `GoogleAuthenticatorLoginDelegate` and `GoogleAuthenticatorSignupDelegate`.
And an honorable mention:
The `SVProgressHUD` that is displayed after selecting a Google account always said `Completing Signup`. That was misleading (and a bit scary) when signup was …

Refactor Google signup logic

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Authenticator/WordPressSupportSourceTag.swift
WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Unified Auth/GoogleAuthViewController.storyboard
WordPressAuthenticator/Unified Auth/GoogleAuthViewController.swift

Ref #282 
To support unified Google flows, this adds:
- An `enableUnifiedGoogle` setting to `WordPressAuthenticatorConfiguration`.
- `GoogleAuthViewController` and storyboard to display a 'waiting for Google' view.
- This view is the same as is displayed in the current Google _signup_ flow. The UI will be updated later.
- If `enableUnifiedGoogle` is enabled, `GoogleAuthViewController` will be displayed for both Google login and signup flows.
Caveats:
- Right now, `GoogleAuthViewController` doesn't actually do any Google-y goodness. It just shows a view after selecting either `Continue with Google` option. The intent is for all Google authentication to be facilitated by this view.
- To easily differentiate this view from the old one (displayed in the Google _signup_ flow), the displayed …

ULS: Adding new VC to be displayed for both Google flows

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/View Related/SiteAddress.storyboard
WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift

Ref. #283 
Ref. https://github.com/wordpress-mobile/WordPress-iOS/pull/14227
This PR: 
- creates a `View Related` folder 
- adds the `SiteAddress.storyboard` 
- adds a mostly blank `SiteAddressViewController` with a temporary label
- navigates to the new `SiteAddressViewController` when using a dev build
2. `bundle exec pod install`
3. build (with no errors)
4. Check out the referenced PR to test changes: https://github.com/wordpress-mobile/WordPress-iOS/pull/14227

UL&S: navigate to blank site address view controller

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift

Ref: #182 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14242
This adds a new `WordPressAuthenticatorUnifiedStyle` to contain styles specific to the unified flows.
Right now, it only contains the view background color as that's all that's needed. We'll add to it as more styles are required.
The initial idea was for the style to be set according to the unified flows being enabled/disabled. However, just because a unified flow is enabled doesn't mean that's what's being presented. Meaning if the new background color were used in `LoginViewController`, the background color will change for _all_ views, not just the specific unified ones.
Instead, each `ViewController` in unified paths will have to override `styleBackground` so it gets the right color …

ULS: Add new style struct for unified styles 

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuthViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Google/GoogleSignupConfirmationViewController.swift

Ref: #282 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14258
When `Next` is tapped on the Google Signup Confirmation view, account creation is now attempted. If successful, the Signup Epilogue will be displayed.
On the off chance a user goes off somewhere else and creates a WP account with the selected Google account _while this view is still displayed_, the account will be logged in instead and the Login Epilogue displayed. _Unless_ the user has:
- Enabled 2FA on the WP account.
- Disconnected Google on the WP account.
In these cases, an error alert will be displayed. These should be edge cases, so not really worth the effort in attempting to handle them.
Side note: the way I implemented `GoogleAuthenticatorDelegate` didn't quite work out as …

ULS: Create Google account

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec

Ref #https://github.com/wordpress-mobile/WordPress-iOS/issues/13803
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14302
This just updates the Shared and Kit pod versions to make the pod chain happy. Note the podspec check with fail until pod releases have been created. You should be able to test locally with the WPiOS PR.

Update Kit and Shared pods.

---

Podfile
Podfile.lock

Relaxes the dependency constraints in the Podfile to match the change to the Podspec.
When building for local development, this should prevent constantly changing the Podfile every time we change a dependency.

Relax internal dependency constaints in Podfile

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/InstructionTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.xib
WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift

Ref. #283 
This PR adds a basic textfield inside a tableview cell. The cell should look like the Zeplin designs. This PR also abstracts out the row presentation.
1. `bundle exec pod install`
2. Build and run
3. Check out the testing PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14340
**iPhone 11 Pro screenshots**
<a href="https://user-images.githubusercontent.com/1062444/85311821-9e6ad500-b47b-11ea-9c16-e289ca1d524c.png"><img src="https://user-images.githubusercontent.com/1062444/85311821-9e6ad500-b47b-11ea-9c16-e289ca1d524c.png" width="350" /></a>
<a href="https://user-images.githubusercontent.com/1062444/85311854-aaef2d80-b47b-11ea-832b-1e7770c125f4.png"><img src="https://user-images.githubusercontent.com/1062444/85311854-aaef2d80-b47b-11ea-832b-1e7770c125f4.png" …

UL&S: Add TextFieldTableViewCell to SiteAddressViewController

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift

Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/14371
This restores the method that handles logins with an account that:
- Has been used to login via SIWA.
- Does not have a WP password set.
- Has 2FA enabled on the WP account.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14373
For reference, this was broken with https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/284 and https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/286.

Restoring method to handle SIWA passwordless 2FA account login.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib

Ref #283 
Per #308, there is a bug where the button title text was truncating. This PR fixes the truncation.
PR to test fix: https://github.com/wordpress-mobile/WordPress-iOS/pull/14385
Before:
After:
<a href="https://user-images.githubusercontent.com/1062444/85781913-d11b0480-b6eb-11ea-9d3d-194a0c1d459b.png"><img src="https://user-images.githubusercontent.com/1062444/85781913-d11b0480-b6eb-11ea-9d3d-194a0c1d459b.png" width="350" /></a>

UL&S: bug fix: make the TextLinkButtonTableViewCell button word wrap, not truncate

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/View Related/SiteAddressViewController.swift

Ref: #182 
This partially updates the navigation bar to the unified style. 
- It is displayed when large titles are enabled.
- Large titles have been enabled on the new Site Address view, so it will show up there.
- When large titles are disabled, the old nav bar style is used.
Specifically what is done:
- The large title color is set from `largeTitleTextColor` .
- The Back button color is set from `navButtonTextColor`.
- The nav bar background color is set from `navBarBackgroundColor`.
- The bottom line on the nav bar is hidden.
And what is not done:
- The 'Help' button is still white (on the white background, you may not see it, but it's there).
- The app icon is still displayed (it's white, so you may not see it, but it's there).
- The large title font has not been updated.
Can be …

ULS: Partially styled navigation bar

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginViewController.swift

Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/14404
This sets the navigation bar's normal title color to `primaryTitleColor` (which the host apps set as `white`). While the normal title is not shown in the Auth views, its settings are carried over to the host app. Because the color wasn't explicitly set in Auth, it defaulted to black. 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14418

Fix the nav bar's normal title color.

---

Podfile
Podfile.lock
WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginViewController.swift

Ref: #315 
This updates the navigation bar's large title font to use the New York font.
<kbd><img width="472" alt="auth" src="https://user-images.githubusercontent.com/1816888/86839134-45479780-c05e-11ea-8666-889db0221e63.png"></kbd>
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14433

ULS: Use NY font for large titles

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewControllerBase.swift
WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift

Ref: #315 
This removes the host app icon from the unified flow's navigation bar.
**New flows:**
**Old flows:**
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14435

ULS: Don't show host app icon in unified nav bar.

---

WordPressAuthenticator.podspec

Now that the 1.19.1 release has been merged into `develop`, this is just to create a new beta version that includes that fix in 1.20 (the nav bar color https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/314).
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14451

Bump pod version.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift

Fixes: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/318
Ref: #315 
This removes the large titles from the unified flows' navigation bar. It has the same style, except now the title is displayed normally instead of large.
| <img width="355" alt="Screen Shot 2020-07-09 at 2 25 06 PM" src="https://user-images.githubusercontent.com/1816888/87087247-047f8800-c1f0-11ea-9add-82370d3e16cc.png"> | <img width="359" alt="Screen Shot 2020-07-09 at 2 25 50 PM" src="https://user-images.githubusercontent.com/1816888/87087321-1eb96600-c1f0-11ea-897a-f37737318500.png"> |
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14453

ULS: Remove support for large title nav bar.

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator.xcodeproj/xcshareddata/xcschemes/WordPressAuthenticator.xcscheme
WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
WordPressAuthenticator/Signin/LoginUsernamePasswordViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddress.storyboard
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref. #322 
Testing PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14450
In this PR, a new view controller, `SiteCredentialsViewController`, and the basic UI have been added to the SiteAddress.storyboard. This code should look very similar to the `SiteAddressViewController`, as they share several of the same methods, UI, and IBOutlets.
2. `bundle exec pod install`
3. Build and run without errors

UL&S: Navigate to a blank SiteCredentialsViewController

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/NUXViewControllerBase.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref: #315 
This adds functionality to set the `Help` nav button text color based on the nav bar being displayed. It also enables the unified nav bar on the Site Credentials view.
For the unified flows, it is now the same blue as the `Back` button.
<kbd><img width="358" alt="Screen Shot 2020-07-10 at 12 23 19 PM" src="https://user-images.githubusercontent.com/1816888/87186147-394f1600-c2a8-11ea-80b7-d67b95df896c.png"></kbd>
For the original flows, it is still white.
<kbd><img width="356" alt="Screen Shot 2020-07-10 at 12 23 30 PM" src="https://user-images.githubusercontent.com/1816888/87186162-3f44f700-c2a8-11ea-83b8-e5e1e863fd63.png"></kbd>
To note, when tapping `Help` and the `Support` view is displayed, the `Close` button (left bar button) color is incorrect for the unified flow. Stay …

ULS: Update Help button color

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Info.plist
WordPressAuthenticator/Signin/LoginNavigationController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref: #315 
This provides the ability to set the status bar style in each view controller.
Since all views use `LoginViewController`, the default style is set there, which is the current style (`WordPressAuthenticator.shared.style.statusBarStyle`).
Each view controller in the unified flows will need to override `preferredStatusBarStyle` and set it to the new style (`WordPressAuthenticator.shared.unifiedStyle.statusBarStyle`). This has been done in the two new Site Address views.
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14494

ULS: Set status bar style per view controller displayed

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.xib
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLabelTableViewCell.xib
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref. #283 
This PR adds the password type to the `TextfieldTableViewCell` and adds the username and password textfields to `SiteCredentialsViewController`. The "Continue" button is not yet implemented because this PR was getting kinda big.
Test PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14492
1. `bundle exec pod install`
2. Build and run 
3. Visit the test PR to see UI changes

UL&S: SiteCredentialsViewController username and password fields

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddress.storyboard
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref: #283 
This adds the ability to resize the table view width based on device size class. The Site Address and Site Credentials views have been updated to use this functionality.
- For the Regular x Regular size class:
- In portrait, the table is 66% of the view width.
- In landscape, the table is 50% of the view width.
- For all other size classes, the table is 100% of the view width.
In addition, the Continue button width resizes with the table.
To note, this uses the same logic as the WPiOS [Login Epilogue](https://github.com/wordpress-mobile/WordPress-iOS/pull/13860) and [Signup Epilogue](https://github.com/wordpress-mobile/WordPress-iOS/pull/14018).
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14512

ULS: Adjust table widths for iPad

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/Resources/Assets.xcassets/onepassword-button.imageset/Contents.json
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.xib
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Closes #322 
This PR adds the OnePassword functionality to the TextFieldTableViewCell for the site URL textfield. While testing on iOS 12 I discovered a bug where the SiteAddressViewController's Continue button would not enable after typing in a URL. I accidentally used a textfield delegate method that was available for iOS 13 only. So instead I created an IBAction in the TextFieldTableCell and attached it directly to the textfield. 
I also fixed a bug where the OnePassword icon was displaying in the wrong color on the old UI.
WPiOS Test PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14511
**Concerns**
@Gio2018 I'd like your opinion on this PR too, if you have a moment. I had to go back to using tuples to pass some of the actions from the textfield in TextFieldTableViewCell …

UL&S: SiteCredentialsViewController: OnePassword function on username for iOS 12 users

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
WordPressAuthenticator/NUX/NUXViewController.swift
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFA.storyboard
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuthViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/336
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14530
This adds an initial unified 2FA view. It simply contains an empty table, the `Continue` button, and is styled for the unified flows.
<kbd>![2fa_view](https://user-images.githubusercontent.com/1816888/88595108-a0e2c080-d01f-11ea-8380-262f727c3a99.png)</kbd>
For now, it is only displayed from the unified Google flow, for accounts:
- That _do not_ have a WP password set.
- _Does_ have WP 2FA enabled.
Also, the unified Google view has been updated to match the unified style.
- The nav bar, status bar, and background color are the unified colors.
- The nav title is `Waiting...`. …

ULS: 2FA initial view

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/336 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14534
This adds content to the new 2FA view:
- Instructions
- Code field
- When the view first appears, the code field becomes first responder.
- The keyboard type is numeric.
- Text code link
To note, the text link and Continue button are not yet functional.
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-28 at 14 46 33](https://user-images.githubusercontent.com/1816888/88719991-65a8c600-d0e1-11ea-897d-d34db5e474dc.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-28 at 14 48 45](https://user-images.githubusercontent.com/1816888/88720082-883adf00-d0e1-11ea-9248-c41d9cb1696a.png) |

ULS: Add content to 2FA view

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

After comparing Xcode's editing features with @ScoutHarris, I discovered Authenticator uses spaces instead of tabs. To keep the new classes consistent with the old ones, I reformatted the classes to use spaces. There are no code changes in this PR.
This is a non-essential PR so I did not create a new pod version in WPiOS.

Address whitespace issues

---

WordPressAuthenticator.podspec
WordPressAuthenticator/NUX/WPWalkthroughTextField.m
WordPressAuthenticator/UI/LoginTextField.swift

Fixes #342 
Test PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14543
This PR changes the password "eye" icon tint color to match the OnePassword "lock" icon tint color.
As you can see in the code, I had to take a "creative" approach to get this to work. Here are the things that don't work:
- You can’t just set a color in Interface Builder, because it is a custom color (not the correct shade of gray compared to the standard set) and the custom colors weren't previously built into IB (which would handle light & dark modes).
- You can’t just use the `WordPressAuthenticator.shared.style` singleton directly in `WPWalkthroughTextField.m` because `WPWalkthroughTextField` is written in Obj-C. The `WordPressAuthenticator.shared.style` properties live inside a struct. Structs are only …

UL&S: Update the password "eye" icon tint color for the old UI

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFA.storyboard
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuthViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref: #336 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14544
This essentially copies the 2FA code handling logic from the old 2FA VC (`Login2FAViewController`) into the new one (`TwoFAViewController`) to process the entered 2FA code.
An entered code is now validated for length and numeric values. When it is submitted, errors are displayed if the code is incorrect, or the account is logged in.
Also, the Continue button is now pinned to the top of the keyboard.
To  note, the `Text me a code instead` link is not yet functional. 
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-29 at 17 18 09](https://user-images.githubusercontent.com/1816888/88863281-ad058400-d1bf-11ea-80c8-431c059cc8d8.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - …

ULS: Add 2FA code handling

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUp.storyboard
WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift

Ref. #345 
Closes #346 
Test PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14551
This PR navigates the user to a new, blank Sign Up screen if the `.unifiedSignup` flag is enabled. 
**iPhone 11 Pro**
| Light Mode | Dark Mode |
| --- | --- |
| <a href="https://user-images.githubusercontent.com/1062444/88963889-23f95600-d26e-11ea-940e-acec5d68aaeb.png"><img src="https://user-images.githubusercontent.com/1062444/88963889-23f95600-d26e-11ea-940e-acec5d68aaeb.png" width="350" /></a> | <a href="https://user-images.githubusercontent.com/1062444/88963929-2fe51800-d26e-11ea-878b-f8807980cfce.png"><img src="https://user-images.githubusercontent.com/1062444/88963929-2fe51800-d26e-11ea-878b-f8807980cfce.png" width="350" /></a> |

UL&S: Navigate to a blank UnifiedSignUpViewController

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift

Ref: #336 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14550
This copies the logic to request a 2FA code via SMS from the old 2FA VC (`Login2FAViewController`) into the new one (`TwoFAViewController`).
Now, when `Text me a code instead` is tapped:
- An `SMS Sent` HUD is displayed.
- An SMS code is requested.
<kbd>![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-30 at 12 51 19](https://user-images.githubusercontent.com/1816888/88962294-797c3580-d263-11ea-8ae2-3b8a109e39d7.png)</kbd>

ULS: 2FA - request code via SMS

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib
WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUp.storyboard
WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift

Closes #349 
Ref. #345 
Test PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14555
This PR adds the GravatarEmailTableViewCell base UI. The work in the UnifiedSignUpViewController displays an example gravatar email cell. Note that "Send Link by Email" button isn't implemented, nor is this view properly connected to the "sign up with email" view controller yet.
**Design**
**iPhone 11 Pro Max**
| Light mode | Dark mode |
| --- | --- |
| <a href="https://user-images.githubusercontent.com/1062444/89065079-b8c48800-d330-11ea-932b-9b9e2816e560.png"><img src="https://user-images.githubusercontent.com/1062444/89065079-b8c48800-d330-11ea-932b-9b9e2816e560.png" width="350" /></a> | <a href="https://user-images.githubusercontent.com/1062444/89065279-fb866000-d330-11ea-9e55-e85d113220eb.png …

UL&S: Gravatar + Email UITableViewCell base UI and example

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Signin/LoginViewController.swift

Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/336
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14556
This shows the new 2FA view when 2FA'ing Apple accounts. Specifically:
- _Does not_ have a WP password set.
- _Does_ have WP 2FA enabled.
<kbd>![2fa_view](https://user-images.githubusercontent.com/1816888/89067868-55852680-d32d-11ea-8c03-fdba76b5b259.png)</kbd>

ULS: Show unified 2FA view for Apple

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuthViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Password/Password.storyboard
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift

Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/352
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14558
This adds an initial password entry view. It simply contains an empty table, the `Continue` button, and is styled for the unified flows. For now, it is only displayed from the unified Google flow, for accounts with a WP password set.
<kbd>![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-31 at 15 23 02](https://user-images.githubusercontent.com/1816888/89078524-cdf5e280-d341-11ea-80a1-726efd2289b2.png)</kbd>

ULS: password initial view

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift

Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/352
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14567
This adds content to the new Password view:
- Gravatar + email. Currently contains stub info.
- Instructions for Google or Apple. Is not displayed for WP accounts.
- Password field. When the view first appears, the field becomes first responder.
- `Reset your password` link. Is not yet functional.
- The `Continue` button is now pinned to the keyboard. Is not yet functional.
<kbd>![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-03 at 16 06 53](https://user-images.githubusercontent.com/1816888/89231908-8a9aae80-d5a3-11ea-980f-6a15c8dcc763.png)</kbd>

ULS: add content to Password view

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib
WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift

Ref. #345 
Closes #354
Test PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14562
This PR ports the "send magic link" functionality found in SignupEmailViewController to UnifiedSignUpViewController. It's currently bypassing email entry and email validation found in SignupEmailViewController, so if you submit an invalid email address, it will crash (on purpose).
| Send magic link | Magic link sent |
| --- | --- | 
| <a href="https://user-images.githubusercontent.com/1062444/89213653-089e8b80-d58b-11ea-8a18-2cc5af924340.png"><img src="https://user-images.githubusercontent.com/1062444/89213653-089e8b80-d58b-11ea-8a18-2cc5af924340.png" width="350" /></a> | <a href="https://user-images.githubusercontent.com/1062444/89213682-1227f380-d58b-11ea-9579-59fb40f05e45.png"><img …

UL&S: Sign up: send magic link

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib
WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift

Ref: #352 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14573
This refactors the `GravatarEmailTableViewCell`:
- The `gravatarImageView` is now a `CircularImageView`.
- The configure method now accepts and email and a placeholder image.
- If the email is valid, the gravatar is downloaded and displayed.
- If the email is not valid, or there is no gravatar, the `userCircle` gridicon is displayed.
Specifically for the Password view:
- The user's email is now displayed.
- The user's gravatar is displayed, if they have one.
| ![gravatar](https://user-images.githubusercontent.com/1816888/89355178-0108e080-d678-11ea-9b40-30f4bc097565.png) | ![no_gravatar](https://user-images.githubusercontent.com/1816888/89355133-da4aaa00-d677-11ea-83f5-400ee30d05ba.png) | …

ULS: Password view: display user's email and Gravatar

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref: #352 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14589
This change: 
- Copies the password validation from the old password VC (`LoginWPComViewController`) to the new one (`PasswordViewController`). 
- Enables the `Reset your password` link.
- Now shows the new 2FA view in the WP flow if it's in the unified Google flow.
| Invalid Password | Reset Password |
| ![invalid_password](https://user-images.githubusercontent.com/1816888/89467998-d67c5d80-d733-11ea-9168-8773993a5a6c.png) | ![reset_password](https://user-images.githubusercontent.com/1816888/89468018-dda36b80-d733-11ea-93cf-6dbf12001fc8.png) |

ULS Password view: Add password validation and forgot password link action.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Analytics/AnalyticsTracker.swift
WordPressAuthenticator/Analytics/GoogleAuthenticatorTracker.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
WordPressAuthenticatorTests/Analytics/AnalyticsTrackerTests.swift

WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14600
This PR addresses two issues with the analytics tracking in the basic Google authentication flow.
1. It tracks the change of the login flow to a signup flow if the user is logging in with Google, and a matching WPCom account does not exist.
2. It tracks the success of the login flow when logging in through Google, when the WPcom account has a 2FA code set.
In order to make this easier, some changes were made to `AnalyticsTracker`:
1. The context is no longer what's meant to be shared.  We now have an `AnalyticsTracker` singleton to make things easier.
2. The flow is no longer set in each tracking call.  It's guarded so that it's possible for us to track a success step without having to know what flow we're in.  We're …

Fix issues in google auth basic tracking

---

Podfile.lock
WordPressAuthenticator.podspec

Update Auth to use the latest published release of WordPressShared, v `1.11.0-beta.1`. (New sprint, new minor point update.)
`bundle exec pod update WordPressShared`  will show `Installing WordPressShared 1.11.0-beta.1 (was 1.10.0-beta.3 and source changed to https://cdn.cocoapods.org/ from trunk)`

Update Auth to use latest WordPressShared pod

---

WordPressAuthenticator/Signin/LoginViewController.swift

This PR makes a small change to how the appearance of UINavigationBar and UIBarButtonItem instances is handled. 
Prior to this PR the global appearance proxy for UINavigationBar and UIBarButtonItem was being modified.  This had a consequence of the changes carrying over into other parts of the implementing app that might use different styles. 
This PR constrains the changes to UINavigationBar and UIBarButtonItem instances that appear within a LoginNavigationController instance.
To test:
- Confirm the issue by launching an app that implements the Authenticator.
- Set the authenticator's navbar background style via the WordPressAuthenticatorStyle config to something garish (mauve maybe? chartreuse? assert yourself ;) )
- Run the app and go through the auth flow to successfully log in.
- …

Constrain nav bar, and bar button appearance changes to auth classes.

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUp.storyboard
WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignUpViewController.swift

It should not be "SignUp". No WPiOS testing PR because this change will be incorporated when the `SignupMagicLinkViewController` PR is opened.

UL&S: Use consistent naming when referring to "Signup"

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift

WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14604
Disables the old tracking events in `GoogleAuthenticator` when the unified sign in is enabled for Google.
The testing steps are detailed in the WPiOS PR.

Disable old tracking events for Google Sign In

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteCredentialsViewController.swift

Ref. #358 
Testing PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14613
This PR updates the TwoFAViewController with VoiceOver support. 
1. `bundle exec pod install` to ensure 1.23.0-beta.3 appears.

Add VoiceOver support to TwoFAViewController

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Signin/LoginWPComViewController.swift

Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/14620
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14626
In the current login flow (not unified), using a password manager on the Password view:
- If logging in via WordPress, selecting any account will still update the username and password. (This is existing behavior.)
- If logging in via Google or SIWA (with an account that has a WP password), only the password will be used. The username is ignored. (This is new behavior.)

Social account logins: Don't update username when using a password manager.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib

Ref: #352 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14637
This adds password manager support to the unified Password view.
- For iOS13+ it is fully functional.
- For iOS12, the 1Password icon appears on the email field, but is not functional yet. (Pending https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/372.)

ULS Password view: add password manager support

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift
WordPressAuthenticator/NUX/NUXButtonViewController.swift
WordPressAuthenticator/Signin/Login.storyboard
WordPressAuthenticator/Signin/LoginPrologueViewController.swift

Prerequisite for https://github.com/woocommerce/woocommerce-ios/issues/2643
In order for WCiOS to adopt SIWA that comes with the authenticator, we're updating WCiOS to also use the login prologue (the first screen in the `Login.storyboard` with CTAs to log in / sign up). Since WCiOS currently has its own view design, I added a few options to enable the login prologue screen to look as close as the current one.
No user-facing changes are expected in WPiOS from this PR, as all the new options are default to the existing values.
- In `WordPressAuthenticator.showLogin`, added a callback when the user taps on the login button
- In WCiOS, we have custom logging on this action and would like to keep it for existing funnels. It also doesn't look like any event is logged on Tracks upon login …

Update login prologue options for WCiOS customizations

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift

Ref: #352 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14647
For SIWA accounts that have a WP password set, this updates the flow to show the new Password and 2FA views.
| Password | 2FA |
| ![password](https://user-images.githubusercontent.com/1816888/90188513-d0602f80-dd78-11ea-943f-c11a21d11e29.png) | ![2fa](https://user-images.githubusercontent.com/1816888/90188520-d48c4d00-dd78-11ea-8047-d96272cbe92e.png) |

ULS: Show new Password and 2FA views in SIWA path

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift

Ref: #352 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14651
When tapping the 1Password on the email address field, 1Password is now launched.
**NOTE**: To facilitate testing, I've commented out the iOS version check. Before this is merged, I will re-enable it so the button only appears for iOS12.
<kbd>![1password_button](https://user-images.githubusercontent.com/1816888/90294405-8bed9600-de43-11ea-9747-57f0d636f1bc.jpg)</kbd>

ULS Password: add 1Password button action

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.xib

Ref: #352 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14652
This adds VoiceOver support to the unified Password view.

ULS Password view: Add VoiceOver support

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginViewController.swift

Ref: #336 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14664
This shows the unified 2FA view in the unified Site Address flow.
<kbd>![2fa](https://user-images.githubusercontent.com/1816888/90460018-32de6600-e0c0-11ea-9a6f-cddf8732b606.png)</kbd>

ULS: Show unified 2FA view in Site Address flow.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/View Related/2FA/TwoFAViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Google/GoogleSignupConfirmationViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift

Ref: #282 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14670
This removes the Waiting for Google view from the navigation stack when these views are displayed so that it's not redisplayed when `Back` is tapped.
- `GoogleSignupConfirmationViewController`
- `PasswordViewController`
- `TwoFAViewController`
<kbd>![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-18 at 14 11 31](https://user-images.githubusercontent.com/1816888/90560752-d2513680-e15c-11ea-91ff-185500397571.png)</kbd>

ULS: Remove the Waiting for Google view from the navigation stack.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginEmailViewController.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift

Ref: #182 
Can be tested with WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14687
When the Social Error is presented, these actions have been fixed:
- `Try with another email` - dismisses the Waiting for Google view and returns to the prologue (effectively the same as it was before the Waiting for Google view was introduced).
- `Try with the site address` - now redirects to the unified Site Address if enabled.
To note, `LoginEmailViewController` forces showing the original Site Address flow since WP email login has not been updated yet, and we don't want to switch UIs midstream.

ULS: Fix actions from Social Error

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Site Address/SiteAddressViewController.swift

Ref: #283 
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14696
This sets `accessibilityIdentifier`s used for WPiOS UI login tests.

ULS Site Address: set accessibility identifiers used by WPiOS UI tests.

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift

Fixes #405
Test PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14749
(Branched from `main`, release tag `1.23.0`. 
This PR changes the Tracks event step name from `username_password` to `password_challenge`.
Please visit the Test PR for testing steps.

UL&S: Tracks: rename step `username_password` to `password_challenge`

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift

Fixes #408 
Testing PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14752
After an error message occurs, the email address would disappear from the display. Sometimes the gravatar would also be wiped out and a crash would happen. This affects SIWA and Google accounts that connect to an existing WP user for the first time. 
Have a WordPress.com account that is disconnected from Google or SIWA.
2. Disable the check for `.isOnePasswordEnabled` by visiting `WPStyleGuide+Login` and commenting out Lines 64-65. (Or you can check out the "Workaround - show password icon in the sims" commit.
3. Build and run
4. See testing PR for further instructions

UL&S: Password challenge bugfix

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
WordPressAuthenticator/Model/LoginFields.swift
WordPressAuthenticator/Signin/LoginPrologueViewController.swift
WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
WordPressAuthenticator/Unified Auth/StoredCredentialsPicker.swift
WordPressAuthenticatorTests/Analytics/AnalyticsTrackerTests.swift

Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/14734
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14760
This PR:
- Implements the iCloud Keychain configuration flag.
- Implements tracking support for iCloud Keychain flow events.
- Adds class `StoredCredentialsAuthenticator` to support the iCloud Keychain login flow (and the quick AppleID login flow in the future).
- Adds class `StoredCredentialsPicker` as a thin wrapper around `ASAuthorizationController` for convenience. 
For more details and testing steps please refer to the WPiOS PR.

UL&S iCloud Keychain: Basic implementation

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Login/LoginMagicLinkViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.xib

Ref. #398 
Test PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14746
This PR
- adds the ability to send a magic link on the password entry screen
- updates the button color in Unified to "hero blue" instead of `.brand`
- doesn't have Tracks events
See testing instructions on the testing PR https://github.com/wordpress-mobile/WordPress-iOS/pull/14746
| Design | Screenshot |
| --- | --- |
| <img width="344" alt="Screen Shot 2020-08-24 at 8 12 28 AM" src="https://user-images.githubusercontent.com/1062444/91182398-bd6e2900-e6af-11ea-8447-206884d5bb01.png"> | <a href="https://user-images.githubusercontent.com/1062444/91183386-0672ad00-e6b1-11ea-82d1-13e50029122d.png"><img src="https://user-images.githubusercontent.com/1062444/91183386-0672ad00-e6b1-11ea-82d1-13e50029122d.png" …

UL&S: PasswordViewController: send a magic link

---

WordPressAuthenticator.podspec
WordPressAuthenticator.xcodeproj/project.pbxproj
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextLinkButtonTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextWithLinkTableViewCell.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextWithLinkTableViewCell.xib

Ref: #404 
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14769
This adds a new `TextWithLinkTableViewCell` that displays a button with the title containing regular text + linked text.
This is used in the Get Started view to display the login Terms of Service. Tapping the button (the entire text area) will open the TOS web page.
| ![get_started_tos](https://user-images.githubusercontent.com/1816888/91355906-11f6ce80-e7ac-11ea-8d7e-d9a8638dbbad.png) | ![tos_page](https://user-images.githubusercontent.com/1816888/91355919-16bb8280-e7ac-11ea-98dc-79e1d7dfdc61.png) |

ULS Get Started: add Terms of Service table cell

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Authenticator/WordPressAuthenticatorDisplayStrings.swift
WordPressAuthenticator/Unified Auth/View Related/Get Started/GetStartedViewController.swift
WordPressAuthenticator/Unified Auth/View Related/Reusable Views/TextFieldTableViewCell.swift

Ref: #404 
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14771
This shows an Email Address field in the Get Started view. It doesn't do anything yet.
To note, it is _not_ made first responder because the keyboard will cover the social options at the bottom (coming soon). If you tap in the email field, the keyboard will then show.
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-26 at 16 30 48](https://user-images.githubusercontent.com/1816888/91363280-88e69400-e7b9-11ea-9ab8-9187b041d6ac.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-26 at 16 30 51](https://user-images.githubusercontent.com/1816888/91363291-8f750b80-e7b9-11ea-980d-822bd29b6ef4.png) |

ULS Get Started: add Email Address field

---

WordPressAuthenticator.podspec
WordPressAuthenticator/Signin/LoginWPComViewController.swift

WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14772
The original issue was that the App was prompting the user to update their password in the keychain, in a scenario where the user was dismissing the VC by pressing "< Back".
Please check the WPiOS PR for reproduction and testing instructions.

Fixes an issue with the save password prompt.

---

WordPressAuthenticator/Signin/LoginSocialErrorViewController.swift
WordPressAuthenticator/Signin/LoginViewController.swift
WordPressAuthenticator/Unified Auth/GoogleAuthenticator.swift
WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuth.storyboard

Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/282
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14779
This fixes several issues in the unified Google flow:
- The Waiting for Google view is now removed when the Social Error view is dismissed by a means other than selecting an option (i.e dragging down, tapping off).
- On the Social Error view, the signup option is no longer shown for unified social flows. 1) It was showing the old signup, mucking up the nav bar. 2) At this point, we've already tried signup, so allowing this option is pointless.
- The `Processing Account` message has been removed from the HUD.
- The Waiting for Google image is now a proper size on iPad.
Note: The podspec version has been updated to `1.23.3` in the `1.23.3` …

ULS: fix unified Google issues

---

WordPressAuthenticator/NUX/NUXViewControllerBase.swift

Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/315
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14781
This fixes the nav bar colors when Support is shown from a unified Auth view in iOS12. 
- When Support is shown, it uses the host app nav bar style.
- When it is dismissed, the Auth views use the unified nav bar style.
Note: The podspec version has been updated to `1.23.3` in the `1.23.3` branch, so it's not updated here.
For reference - this fix is basically backporting this change that is already in `develop` - https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/402/files#diff-e5d0c11414c47546041eebbd700297f2
| ![site_address](https://user-images.githubusercontent.com/1816888/91506308-0cbe8000-e88f-11ea-8636-a80452189765.png …

ULS: correct nav bar colors in iOS12
