wordpress-mobile/WordPressAuthenticator-iOS

- WordPressAuthenticator/Extensions/UIImage+Assets.swift
PR #6 was merged against `master`. In this PR we're just cherry-picking the fix, and resubmitting against `develop` instead.
cc @aerych @loremattei (Thank you both in advance!!)
> Backporting: Missing Asset Fix

- WordPressAuthenticator/Extensions/UIImage+Assets.swift
This PR merges the branch that fixed a missing asset issue for an already released version of WPiOS
> Fix missing asset

- WordPressAuthenticator.podspec
Bump .podspec version to 1.0.1
(Can't make commits directly to develop, hence the quick PR)
> Bump version to 1.0.1

- WordPressAuthenticator.podspec
Bump the pod spec version to 1.1.9 for release.
> Bump pod spec version to 1.1.9

- WordPressAuthenticator.podspec
Merge release/1.1.10 into develop
> Merge release/1.1.10 into develop

- Podfile
- Podfile.lock
- WordPressAuthenticator.podspec
- WordPressAuthenticator/Services/SignupService.swift
- WordPressAuthenticator/Services/WordPressComBlogService.swift
- WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
Merge Release/1.1.10 into Master
> Merge Release/1.1.10 into Master

- WordPressAuthenticator.podspec
Merge release 1.2.0 into develop
> Merge release 1.2.0 into develop

- WordPressAuthenticator.podspec
Merge release/1.2.0 into Master
> Merge release/1.2.0 into Master

- WordPressAuthenticator.podspec
Doing a new release to include the changes from 1.3.1 and 1.4.0-beta.1
> Bump version to 1.4.0-beta.2

- WordPressAuthenticator.podspec
This updates the pod version (that should have been done with #85).
> Bumping WPAuth pod version.

- WordPressAuthenticator.podspec
Prevents potential dependency issues
> Sync up dependencies with podspec

- WordPressAuthenticator.podspec
- WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
- WordPressAuthenticator/Signin/LoginEmailViewController.swift
- WordPressAuthenticator/Signin/LoginPrologueLoginMethodViewController.swift
- WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift
- WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift
Merge Release/1.10.1 into Master
> Merge Release/1.10.1 into Master

- WordPressAuthenticator.podspec
> Release 1.10.2

- WordPressAuthenticator.podspec
Merge release/1.10.3 into develop
> Merge release/1.10.3 into develop

- WordPressAuthenticator.podspec
Merge Release 1.10.5 into develop
> Merge Release 1.10.5 into develop

- WordPressAuthenticator.podspec
Merge release/1.10.6 into develop
> Merge release/1.10.6 into develop

- WordPressAuthenticator.podspec
Merge release/1.10.7 into develop
> Merge release/1.10.7 into develop

- WordPressAuthenticator.podspec
Merge release/1.10.8 into develop
> Merge release/1.10.8 into develop

- WordPressAuthenticator.podspec
> Release 1.10.9

- Podfile
- Podfile.lock
- WordPressAuthenticator.podspec
- Update Gridicons to version 0.20.beta.1
> Update to version 1.11.0-beta.2

- Podfile
- Podfile.lock
- WordPressAuthenticator.podspec
- WordPressAuthenticator.xcodeproj/xcshareddata/xcschemes/WordPressAuthenticator.xcscheme
Also updates the shared scheme to Xcode 11
To test:
- run pod install and verify that the framework builds correctly
> Update version of NSURL+IDN to 0.4

- Podfile
- Podfile.lock
- WordPressAuthenticator.podspec
Merge release/1.11.0 back into develop
> Merge release/1.11.0 back into develop

- WordPressAuthenticator.podspec
- WordPressAuthenticator/Extensions/WPStyleGuide+Login.swift
- WordPressAuthenticator/NUX/NUXButton.swift
This merges the hotfixes created for WPiOS 14.5 back into the develop branch.
> Merge `master` into `develop`

- Podfile
- Podfile.lock
- WordPressAuthenticator.podspec
Merge release 1.12 into develop
> Merge release 1.12 into develop

- Podfile
- Podfile.lock
- WordPressAuthenticator.podspec
Merge release/1.13 back into develop
> Merge release/1.13 back into develop

- WordPressAuthenticator.podspec
- WordPressAuthenticator/NUX/NUXViewController.swift
Fixes #253 
Ref. #182 
This PR deletes a case that was declared but never used. Since it's not used anywhere, I didn't create test PRs for the host apps.
> UL&S: Remove .showMagicLink

- Podfile
- Podfile.lock
- WordPressAuthenticator.podspec
Merge Release/1.15.0 into develop
> Merge Release/1.15.0 into develop

- WordPressAuthenticator.podspec
Merge release/1.16 into develop
> Merge release/1.16 into develop

- Podfile
- Podfile.lock
- WordPressAuthenticator.podspec
> Release/1.16.1 - Update to WordPressUI 1.7.0

- WordPressAuthenticator.podspec
- WordPressAuthenticator/Authenticator/WordPressAuthenticatorConfiguration.swift
Add a feature flag that will enable the unified site address login flow.
> UL&S: Add a feature flag for unified site address login

- Podfile
- Podfile.lock
- WordPressAuthenticator.podspec
Merge Release/1.17 into develop
> Merge Release/1.17 into develop

- WordPressAuthenticator.podspec
- WordPressAuthenticator/Signin/LoginPrologueViewController.swift
- WordPressAuthenticator/Signin/LoginViewController.swift
This is simply to merge the https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/331 fix into `develop`.
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14510
> Merge SIWA fix into develop

- WordPressAuthenticator.podspec
- WordPressAuthenticator/Signin/LoginViewController.swift
- WordPressAuthenticator/Unified Auth/View Related/Google/GoogleAuthViewController.swift
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14662
Implements all remaining tracking for Google Sign In.
Please refer to the WPiOS PR for details and testing steps.
> Completes Google tracking for UL&S

- WordPressAuthenticator.podspec
- WordPressAuthenticator.xcodeproj/project.pbxproj
The `LoginMagicLinkViewController` class and `UnifiedLogin.storyboard` will eventually live in this folder.
> UL&S: add Login folder to unified auth

- WordPressAuthenticator.podspec
- WordPressAuthenticator/Extensions/UIStoryboard+Helpers.swift
- WordPressAuthenticator/Signin/LoginPrologueViewController.swift
- WordPressAuthenticator/Unified Auth/View Related/Sign up/SignupMagicLinkViewController.swift
- WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignup.storyboard
- WordPressAuthenticator/Unified Auth/View Related/Sign up/UnifiedSignupViewController.swift
Ref. #345 
Testing PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14659
This PR implements the "Open Mail" button logic from NUXLinkMailViewController.
> UL&S: SignupMagicLinkViewController: Open Mail 

- WordPressAuthenticator.podspec
Merge release/1.23 back into develop
> Merge release/1.23 back into develop

- WordPressAuthenticator.podspec
- WordPressAuthenticator/Analytics/AuthenticatorAnalyticsTracker.swift
- WordPressAuthenticator/Unified Auth/View Related/Password/PasswordViewController.swift
- WordPressAuthenticator/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
Bring the `1.23.1` and `1.23.2` release updates into `develop`.
> Merge `main` into `develop`

- WordPressAuthenticator.podspec
- WordPressAuthenticator/Signin/LoginPrologueViewController.swift
- WordPressAuthenticator/Signin/LoginViewController.swift
- WordPressAuthenticator/Unified Auth/StoredCredentialsAuthenticator.swift
Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/14734
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14770
This PR implements the basic login flow for the iCloud Keychain authentication flow.
Please refer to the WPiOS PR for details on how to test this.
> UL&S iCloud Keychain: Simple successful login path
